workspace(name = "pt_asm_java_agent")

# LOAD HELPER FUNCTIONS FROM ROOT WORKSPACE

local_repository(
    name = "phasicj",
    path = "../../../..",
)

load(
    "@phasicj//bazel:external_repositories.bzl",
    "rules_jvm_external",
    "dwtj_rules_java",
)

# CONFIGURE `@dwtj_rules_java` ################################################

dwtj_rules_java()

load(
    "@dwtj_rules_java//java:repositories.bzl",
    "dwtj_local_openjdk_repository",
    "remote_google_java_format_repository",
    "maven_error_prone_repository",
)

# CONFIGURE `@local_openjdk_repository` #######################################

dwtj_local_openjdk_repository(
    name = "dwtj_local_openjdk",
)

load("@dwtj_local_openjdk//:defs.bzl", "register_java_toolchains")

register_java_toolchains()

# CONFIGURE `@google_java_format` #############################################

remote_google_java_format_repository(
    name = "google_java_format",
)

load('@google_java_format//:defs.bzl', 'register_google_java_format_toolchain')

register_google_java_format_toolchain()

# CONFIGURE `@rules_jvm_external` and `@maven` ################################

rules_jvm_external()

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "org.ow2.asm:asm:8.0.1",
    ],
    repositories = [
        "https://jcenter.bintray.com/",
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
    # NOTE(dwtj): Fetching sources to help developers during development. They
    #  aren't used during building or testing.
    fetch_sources = True,
)

# CONFIGURE `@error_prone` ####################################################

maven_error_prone_repository(
    name = "error_prone",
)

load(
    "@error_prone//:defs.bzl",
    "fetch_error_prone_toolchain",
    "register_error_prone_toolchain",
)

fetch_error_prone_toolchain()
register_error_prone_toolchain()
