load("@dwtj_rules_java//java:defs.bzl", "dwtj_java_library")

dwtj_java_library(
    name = "rt",
    srcs = ["ApplicationEvents.java"],
    output_jar = "rt.jar",
    visibility = ["//phasicj/agent:__subpackages__"],
)

# TODO(dwtj): Create embedded JAR and Rust bindings to access it.
