load("@dwtj_rules_java//java:defs.bzl", "dwtj_java_binary")

package(
    default_visibility = ["//phasicj/test:__subpackages__"],
)

dwtj_java_binary(
    name = "hello_synchronized",
    srcs = ["HelloSynchronized.java"],
    main_class = "phasicj.test.java_apps.HelloSynchronized",
    output_jar = "hello_synchronized.jar",
)
