workspace(name = "pt_asm_renaissance")

# CONFIGURE `@phasicj` ########################################################

local_repository(
    name = "phasicj",
    path = "../../../..",
)

load(
    "@phasicj//bazel:external_repositories.bzl",
    "dwtj_rules_java",
    "com_github_renaissance_benchmarks",
    "org_ow2_asm",
)

# CONFIGURE `@dwtj_rules_java` ################################################

dwtj_rules_java()

load("@dwtj_rules_java//java:repositories.bzl", "dwtj_local_openjdk_repository")
dwtj_local_openjdk_repository(
    name = "dwtj_local_openjdk"
)

load("@dwtj_local_openjdk//:defs.bzl", "register_java_toolchains")
register_java_toolchains()

# CONFIGURE `@com_github_renaissance_benchmarks` ##############################

com_github_renaissance_benchmarks()

# CONFIGURE `@org_ow2_asm` ####################################################

org_ow2_asm()
