workspace(name = "pt_asm_renaissance")

# CONFIGURE `@phasicj` ########################################################

local_repository(
    name = "phasicj",
    path = "../../../..",
)

load(
    "@phasicj//bazel:external/repositories.bzl",
    "com_github_renaissance_benchmarks",
    "dwtj_rules_java",
    "org_ow2_asm",
    "apply_remote_graalvm_linux_repository",
)

# CONFIGURE `@dwtj_rules_java` ################################################

dwtj_rules_java()

load("@dwtj_rules_java//graalvm:repositories.bzl", "remote_graalvm_repository")

apply_remote_graalvm_linux_repository(
    "graalvm_linux_x64",
    remote_graalvm_repository,
)

load("@graalvm_linux_x64//java:defs.bzl", "register_java_toolchains")

register_java_toolchains()

# CONFIGURE `@com_github_renaissance_benchmarks` ##############################

com_github_renaissance_benchmarks()

# CONFIGURE `@org_ow2_asm` ####################################################

org_ow2_asm()
