FROM registry.fedoraproject.org/fedora:33

# Update Base Fedora Image ####################################################
RUN dnf update --assumeyes

# Install dependencies ########################################################
WORKDIR /container/setup

COPY setup/* .
RUN ./install_dnf_dependencies.sh
RUN ./install_npm_dependencies.sh
RUN ./install_cargo_dependencies.sh

# Download, verify, and install Bazelisk.
ARG bazelisk_url="https://github.com/bazelbuild/bazelisk/releases/download/v1.7.4/bazelisk-linux-amd64"
ARG bazelisk_sha256_file="bazelisk-linux-amd64.sha256"
RUN ./install_bazelisk.sh "$bazelisk_url" "$bazelisk_sha256_file"

# Define Some Build Image Constants ###########################################

# Declare customizable mount points as build arguments.
ARG phasicj_edge_repo_dir="/root/phasicj.git"
ARG phasicj_build_repo_dir="/root/phasicj.build"
ARG bazel_cache_dir="/root/.cache/bazel"
ARG bazelisk_cache_dir="/root/.cache/bazelisk"
ARG msmtp_config_dir="/root/.config/msmtp"

# Make these customizable mount points environment variables.
ENV PHASICJ_EDGE_REPO_DIR="$phasicj_edge_repo_dir"
ENV PHASICJ_BUILD_REPO_DIR="$phasicj_build_repo_dir"
ENV BAZEL_CACHE_DIR="$bazel_cache_dir"
ENV BAZELISK_CACHE_DIR="$bazelisk_cache_dir"
ENV MSMTP_CONFIG_DIR="$msmtp_config_dir"

ARG ssh_authorized_keys_file="/root/.ssh/authorized_keys"
ENV SSH_AUTHORIZED_KEYS_FILE="$ssh_authorized_keys_file"

# Specify the PhasicJ repository from which the edge repository should be
# cloned.
ARG phasicj_edge_repo_origin="https://github.com/dwtj/phasicj.git"

# Create Initial Contents of Cache Volumes ####################################

# NOTE(dwtj): We use `touch` to make empty files to help run scripts detect
# whether these cache volumes have been mounted appropriately.

RUN mkdir -p "$bazel_cache_dir" && touch "${bazel_cache_dir}/.bazel_cache_volume_root"
VOLUME "$bazel_cache_dir"

RUN mkdir -p "$bazelisk_cache_dir" && touch "${bazelisk_cache_dir}/.bazelisk_cache_volume_root"
VOLUME "$bazelisk_cache_dir"

RUN git clone --bare "$phasicj_edge_repo_origin" "$phasicj_edge_repo_dir"
COPY config/user/git/hooks/* "$phasicj_edge_repo_dir/hooks/"
VOLUME "$phasicj_edge_repo_dir"

RUN git clone --origin edge "$phasicj_edge_repo_dir" "$phasicj_build_repo_dir" && \
    cd "$phasicj_build_repo_dir" && \
    git config advice.detachedHead false
VOLUME "$phasicj_build_repo_dir"

# Configure Email Send ########################################################
# NOTE(dwtj): The msmtp config is expected to contain secrets, so we don't
# include it in the image build. It needs to be mounted at container run-time.
COPY config/user/mailrc /root/.mailrc
COPY config/etc/aliases.msmtp /etc/aliases.msmtp

# Configure SSH Server ########################################################
COPY config/etc/ssh/sshd_config.d/* /etc/ssh/sshd_config.d

# Configure the User's SSH Login ##############################################
COPY config/user/ssh /root/.ssh

# Install Scripts #############################################################
COPY config/user/bin/* /root/bin/

# Setup the Default Run Command ###############################################
COPY run/default.sh /container/run/default.sh

WORKDIR /root

CMD /container/run/default.sh
