workspace(name = "pt_rust_jvmti_agent")

# CONFIGURE `@phasicj` ########################################################

local_repository(
    name = "phasicj",
    path = "../../../..",
)

load(
    "@phasicj//bazel:external/repositories.bzl",
    "apply_dwtj_remote_openjdk_repository",
    "bazel_skylib",
    "dwtj_rules_java",
    "io_bazel_rules_rust",
)

# CONFIGURE `@bazel_skylib` ###################################################
# This dependency is needed for `@io_bazel_rules_rust`. Here we set it to a
# particular version (instead of using the version used in the
# `rust_repositories()` macro below).

bazel_skylib()

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

# CONFIGURE `@io_bazel_rules_rust` ############################################

io_bazel_rules_rust()

load("@io_bazel_rules_rust//rust:repositories.bzl", "rust_repositories")

rust_repositories()

load("@io_bazel_rules_rust//:workspace.bzl", "rust_workspace")

rust_workspace()

# CONFIGURE `@dwtj_rules_java` ################################################

dwtj_rules_java()

load("@dwtj_rules_java//java:repositories.bzl", "dwtj_remote_openjdk_repository")

apply_dwtj_remote_openjdk_repository(
    "openjdk_linux_x64",
    dwtj_remote_openjdk_repository,
)

load("@openjdk_linux_x64//java:defs.bzl", "register_java_toolchains")

register_java_toolchains()
