workspace(name = "pt_rust_grpc_ipc")

# CONFIGURE `@phasicj` ########################################################

local_repository(
    name = "phasicj",
    path = "../../../../..",
)

load(
    "@phasicj//bazel:external/repositories.bzl",
    "rules_rust",
    "rules_proto",
    "platforms",
)

# CONFIGURE `@rules_proto` ####################################################

rules_proto()

load(
    "@rules_proto//proto:repositories.bzl",
    "rules_proto_dependencies",
    "rules_proto_toolchains",
)

rules_proto_dependencies()
rules_proto_toolchains()

# CONFIGURE `@rules_rust` #####################################################

rules_rust()

load("@rules_rust//rust:repositories.bzl", "rust_repositories")
load("@rules_rust//proto:repositories.bzl", "rust_proto_repositories")

rust_repositories(edition = "2018")

rust_proto_repositories(register_default_toolchain = True)

# CONFIGURE cargo-raze ########################################################

load("//third_party/cargo:crates.bzl", "raze_fetch_remote_crates")

raze_fetch_remote_crates()

# CONFIGURE `@platforms` ######################################################

platforms()
