workspace(name = "pt_rust_grpc_ipc")

# CONFIGURE `@phasicj` ########################################################

local_repository(
    name = "phasicj",
    path = "../../../../..",
)

load(
    "@phasicj//bazel:external/repositories.bzl",
    "rules_rust",
)

# CONFIGURE `@rules_proto` ####################################################

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

RULES_PROTO_COMMIT = "c0b62f2f46c85c16cb3b5e9e921f0d00e3101934"
RULES_PROTO_SHA256 = "e0cab008a9cdc2400a1d6572167bf9c5afc72e19ee2b862d18581051efab42c9"

http_archive(
    name = "rules_proto",
    sha256 = RULES_PROTO_SHA256,
    strip_prefix = "rules_proto-{}".format(RULES_PROTO_COMMIT),
    url = "https://github.com/bazelbuild/rules_proto/archive/{}.tar.gz".format(RULES_PROTO_COMMIT),
)

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")

rules_proto_dependencies()
rules_proto_toolchains()

# CONFIGURE `@rules_rust` #####################################################

rules_rust()

load("@rules_rust//rust:repositories.bzl", "rust_repositories")
load("@rules_rust//proto:repositories.bzl", "rust_proto_repositories")

rust_repositories(edition = "2018")

rust_proto_repositories(register_default_toolchain = True)

# CONFIGURE cargo-raze ########################################################

load("//third_party/cargo:crates.bzl", "raze_fetch_remote_crates")

raze_fetch_remote_crates()
