workspace(name = "pt_asm_jvmti_agent")

# CONFIGURE `@phasicj` ########################################################

local_repository(
    name = "phasicj",
    path = "../../../..",
)

load(
    "@phasicj//bazel:external_repositories.bzl",
    "com_github_renaissance_benchmarks",
    "dwtj_rules_java",
    "org_ow2_asm",
    "rules_cc",
    "rules_jvm_external",
)

# CONFIGURE `@dwtj_rules_java` ################################################

dwtj_rules_java()

load(
    "@dwtj_rules_java//java:repositories.bzl",
    "dwtj_local_openjdk_repository",
    "maven_error_prone_repository",
    "remote_google_java_format_repository",
)

dwtj_local_openjdk_repository(
    name = "dwtj_local_openjdk",
)

load("@dwtj_local_openjdk//:defs.bzl", "register_java_toolchains")

register_java_toolchains()

# CONFIGURE `@google_java_format` #############################################

remote_google_java_format_repository(
    name = "google_java_format",
)

load("@google_java_format//:defs.bzl", "register_google_java_format_toolchain")

register_google_java_format_toolchain()

# CONFIGURE `@rules_jvm_external` #############################################

#rules_jvm_external()

# CONFIGURE `@maven_error_prone` ##############################################

# TODO(dwtj): Fix the problem with Error Prone, and re-enable it.
#maven_error_prone_repository(
#    name = "maven_error_prone",
#)
#
#load("@maven_error_prone//:defs.bzl", "register_error_prone_toolchain")
#
#register_error_prone_toolchain()

# CONFIGURE `@com_github_renaissance_benchmarks` ##############################

com_github_renaissance_benchmarks()

# CONFIGURE `@org_ow2_asm` ####################################################

org_ow2_asm()

# CONFIGURE `@rules_cc` #######################################################

rules_cc()
