load("@dwtj_rules_java//java:defs.bzl", "dwtj_java_library")

dwtj_java_library(
    name = "instr",
    srcs = ["Instrumenter.java"],
    visibility = ["//phasicj/agent:__subpackages__"],
    deps = ["//third_party/asm"],
)
