load("@dwtj_rules_java//java:defs.bzl", "dwtj_java_library")

dwtj_java_library(
    name = "svm",
    srcs = ["Instrumenter.java"],
    deps = ["//phasicj/agent/instr"],
    visibility = ["//phasicj/agent/experimental/svm:__subpackages__"],
)
