workspace(name = "pt_graal_shadow_vm")

# CONFIGURE `@phasicj` ########################################################

local_repository(
    name = "phasicj",
    path = "../../../..",
)

load(
    "@phasicj//bazel:external_repositories.bzl",
    "dwtj_rules_embed",
    "dwtj_rules_java",
    "io_bazel_rules_rust",
    "apply_remote_graalvm_repository",
    "rules_cc",
)

# CONFIGURE `@dwtj_rules_java` ################################################

dwtj_rules_java()

load(
    "@dwtj_rules_java//graalvm:repositories.bzl",
    "remote_graalvm_repository",
)

# CONFIGURE `@graalvm_linux_x64` ##############################################

apply_remote_graalvm_repository(
    "graalvm_linux_x64",
    remote_graalvm_repository,
)

load("@graalvm_linux_x64//:defs.bzl", "register_java_toolchains")

register_java_toolchains()

load("@graalvm_linux_x64//graalvm:defs.bzl", "register_graalvm_toolchains")

register_graalvm_toolchains()

# CONFIGURE `@rules_cc` #######################################################

rules_cc()

# CONFIGURE `@dwtj_rules_embed() ##############################################

dwtj_rules_embed()

# CONFIGURE `@io_bazel_rules_rust` ############################################

io_bazel_rules_rust()

load("@io_bazel_rules_rust//rust:repositories.bzl", "rust_repositories")

rust_repositories()

load("@io_bazel_rules_rust//:workspace.bzl", "rust_workspace")

rust_workspace()
