workspace(name = "pt_graal_shadow_vm")

# CONFIGURE `@phasicj` ########################################################

local_repository(
    name = "phasicj",
    path = "../../../..",
)

load(
    "@phasicj//bazel:external_repositories.bzl",
    "dwtj_rules_embed",
    "dwtj_rules_java",
    "io_bazel_rules_rust",
    "rules_cc",
)

# CONFIGURE `@dwtj_rules_java` ################################################

dwtj_rules_java()

load(
    "@dwtj_rules_java//java:repositories.bzl",
    "dwtj_remote_openjdk_repository",
)
load(
    "@dwtj_rules_java//graalvm:repositories.bzl",
    "local_graalvm_repository",
)

# CONFIGURE REMOTE OPENJDK ####################################################

dwtj_remote_openjdk_repository(
    name = "openjdk_linux_x64",
    os = "linux",
    sha256 = "6e4cead158037cb7747ca47416474d4f408c9126be5b96f9befd532e0a762b47",
    strip_prefix = "jdk-11.0.8+10",
    url = "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.8%2B10/OpenJDK11U-jdk_x64_linux_hotspot_11.0.8_10.tar.gz",
)

load("@openjdk_linux_x64//:defs.bzl", "register_java_toolchains")

register_java_toolchains()

# CONFIGURE `@local_graalvm` ##################################################

local_graalvm_repository(
    name = "local_graalvm",
)

load("@local_graalvm//:defs.bzl", "register_graalvm_toolchains")

register_graalvm_toolchains()

# CONFIGURE `@rules_cc` #######################################################

rules_cc()

# CONFIGURE `@dwtj_rules_embed() ##############################################

dwtj_rules_embed()

# CONFIGURE `@io_bazel_rules_rust` ############################################

io_bazel_rules_rust()

load("@io_bazel_rules_rust//rust:repositories.bzl", "rust_repositories")

rust_repositories()

load("@io_bazel_rules_rust//:workspace.bzl", "rust_workspace")

rust_workspace()
