#!/bin/sh -
#
# This script builds and runs some very basic tests on the architecture
# prototypes. It should be invoked from the root of the repository.

set -e

REPOSITORY_ROOT="$PWD"

cd "${REPOSITORY_ROOT}/architecture/prototypes/instrumentation/pt_asm_java_agent"
bazel build //...
bazel test //...

cd "${REPOSITORY_ROOT}/architecture/prototypes/integration/pt_grpc"
bazel build //...
bazel test //...

cd "${REPOSITORY_ROOT}/architecture/prototypes/benchmarking/pt_instrument_renaissance"
bazel build //...
bazel test //...

cd "${REPOSITORY_ROOT}/architecture/prototypes/benchmarking/pt_jvmti_vs_java_agent"
bazel build //...
bazel test //...
