#!/bin/sh -
#
# This script builds and runs some very basic tests on the architecture
# prototypes. It should be invoked from the root of the repository.

set -e

REPOSITORY_ROOT="$PWD"

cd "${REPOSITORY_ROOT}/architecture/prototypes/integration/pt_asm_java_agent"
bazel build //...
bazel test //...

cd "${REPOSITORY_ROOT}/architecture/prototypes/integration/pt_jvmti_agent_with_embedded_jar"
bazel build //...
bazel test //...

cd "${REPOSITORY_ROOT}/architecture/prototypes/integration/pt_grpc"
bazel build //...
bazel test //...

cd "${REPOSITORY_ROOT}/architecture/prototypes/integration/pt_asm_renaissance"
bazel build //...
bazel test //...

cd "${REPOSITORY_ROOT}/architecture/prototypes/integration/pt_graal_shadow_vm"
bazel build //...
bazel test //...

#cd "${REPOSITORY_ROOT}/architecture/prototypes/benchmarking/pt_jvmti_vs_bytecode_events"
#bazel build //...
#bazel test //...
