workspace(name = "pt_jvmti_agent_with_embedded_jar")

# CONFIGURE `@phasicj` ########################################################

local_repository(
    name = "phasicj",
    path = "../../../..",
)

load(
    "@phasicj//bazel:external/repositories.bzl",
    "dwtj_rules_java",
    "rules_cc",
)

# CONFIGURE `@dwtj_rules_java` ################################################

dwtj_rules_java()

load(
    "@dwtj_rules_java//java:repositories.bzl",
    "known_openjdk_repository",
)

# CONFIGURE REMOTE OPENJDK ####################################################

known_openjdk_repository(
    "openjdk_linux_x64",
)

load("@openjdk_linux_x64//java:defs.bzl", "register_java_toolchains")

register_java_toolchains()

# CONFIGURE `@rules_cc` #######################################################

rules_cc()
