workspace(name = "pt_jvmti_agent_with_embedded_jar")

# CONFIGURE `@phasicj` ########################################################

local_repository(
    name = "phasicj",
    path = "../../../..",
)

load(
    "@phasicj//bazel:external_repositories.bzl",
    "dwtj_rules_java",
    "rules_cc",
)

# CONFIGURE `@dwtj_rules_java` ################################################

dwtj_rules_java()

load(
    "@dwtj_rules_java//java:repositories.bzl",
    "dwtj_remote_openjdk_repository",
)

# CONFIGURE REMOTE OPENJDK ####################################################

dwtj_remote_openjdk_repository(
    name = "net_java_jdk_15_linux_x64",
    url = "https://download.java.net/java/GA/jdk15/779bf45e88a44cbd9ea6621d33e33db1/36/GPL/openjdk-15_linux-x64_bin.tar.gz",
    sha256 = "bb67cadee687d7b486583d03c9850342afea4593be4f436044d785fba9508fb7",
    strip_prefix = "jdk-15",
)

load("@net_java_jdk_15_linux_x64//:defs.bzl", "register_java_toolchains")

register_java_toolchains()

# CONFIGURE `@rules_cc` #######################################################

rules_cc()
