load(":test.bzl", "test")

test(name = "HelloWorld")

# TODO(dwtj): Figure out a way to make the PhasicJ runtime's native methods
#  available during execution of this test. Then re-enable this.
# test(name = "MonitorEnterAndExitInstrs")
