workspace(name = "pt_grpc")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# CONFIGURE `@phasicj` ########################################################
# This external workspace is used to fetch additional external workspaces (e.g.
#  `@rules_proto`).

local_repository(
    name = "phasicj",
    path = "../../../..",
)

load(
    "@phasicj//bazel:external/repositories.bzl",
    "dwtj_rules_java",
    "rules_cc",
    "rules_java",
    "rules_proto",
    "rules_jvm_external",
)

# CONFIGURE `@rules_proto` ####################################################

rules_proto()

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")

rules_proto_dependencies()

rules_proto_toolchains()

# CONFIGURE `@dwtj_rules_java` ################################################

dwtj_rules_java()

load("@dwtj_rules_java//java:repositories.bzl", "known_openjdk_repository")

known_openjdk_repository(
    name = "openjdk_linux_x64",
)

load("@openjdk_linux_x64//java:defs.bzl", "register_java_toolchains")

register_java_toolchains()

# CONFIGURE `@rules_java`

rules_java()

# CONFIGURE `@rules_cc` #######################################################

rules_cc()

# CONFIGURE `@com_github_grpc_grpc` ###########################################

# NOTE(dwtj): This version is used because it is the latest release as I am
#  updating this on 2021-06-18.

_GRPC_TAG = "v1.38.0"

_GRPC_ARCHIVE_PREFIX = "grpc-1.38.0"

_GRPC_SHA256 = "abd9e52c69000f2c051761cfa1f12d52d8b7647b6c66828a91d462e796f2aede"

http_archive(
    name = "com_github_grpc_grpc",
    sha256 = _GRPC_SHA256,
    strip_prefix = _GRPC_ARCHIVE_PREFIX,
    url = "https://github.com/grpc/grpc/archive/{}.tar.gz".format(_GRPC_TAG),
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()

load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")

grpc_extra_deps()

# CONFIGURE `@com_github_grpc_grpc_java` ######################################

# NOTE(dwtj): This version is used because it is the latest release as I am
#  updating this on 2021-06-18.

_GRPC_JAVA_TAG = "v1.38.1"

_GRPC_JAVA_ARCHIVE_PREFIX = "grpc-java-1.38.1"

_GRPC_JAVA_SHA256 = "80119952caa2111abd708e350be01e0615d1510a862cf0151eeae573445f98fa" # v1.38.1
# _GRPC_JAVA_SHA256 = "c454e068bfb5d0b5bdb5e3d7e32cd1fc34aaf22202855e29e048f3ad338e57b2" # v1.38.0

http_archive(
    name = "com_github_grpc_grpc_java",
    sha256 = _GRPC_JAVA_SHA256,
    strip_prefix = _GRPC_JAVA_ARCHIVE_PREFIX,
    url = "https://github.com/grpc/grpc-java/archive/{}.tar.gz".format(_GRPC_JAVA_TAG),
)

load(
    "@com_github_grpc_grpc_java//:repositories.bzl",
    "grpc_java_repositories",
    "IO_GRPC_GRPC_JAVA_ARTIFACTS",
    "IO_GRPC_GRPC_JAVA_OVERRIDE_TARGETS",
)

# Needed for some gRPC-java deps (e.g., `@com_google_code_findbugs_jsr305`).
# See [this example Bazel workspace][1] for a full example.
#
# [1]: https://github.com/grpc/grpc-java/blob/d4fa0ecc07495097453b0a2848765f076b9e714c/examples/WORKSPACE

rules_jvm_external()

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    name = "maven",
    artifacts = IO_GRPC_GRPC_JAVA_ARTIFACTS,
    generate_compat_repositories = True,
    override_targets = IO_GRPC_GRPC_JAVA_OVERRIDE_TARGETS,
    repositories = [
        "https://jcenter.bintray.com/",
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
)

load("@maven//:compat.bzl", "compat_repositories")

compat_repositories()

grpc_java_repositories()

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()
