- name: Install PhasicJ macOS CI Dependencies
  hosts: phasicj_macos_ci
  collections:
    - community.general
  environment:
    # NOTE(dwtj): For some reason, the directory to which Homebrew installs
    #  executables is not on the `PATH` when commands are run by Ansible. So, we
    #  add it manually.
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"

  tasks:
    - name: Homebrew Install OpenJDK
      homebrew:
        name: openjdk
        update_homebrew: yes

    - name: Symlink Homebrew OpenJDK into System JDK Directory
      file:
          src: /usr/local/opt/openjdk/libexec/openjdk.jdk
          dest: /Library/Java/JavaVirtualMachines/openjdk.jdk
          state: link
      become: yes

    - name: Homebrew Install Bazelisk
      homebrew:
        name: bazelisk

    - name: Homebrew Install colordiff
      homebrew:
        name: colordiff

    - name: Homebrew Install Node.js
      homebrew:
        name: node

    - name: Homebrew Install Rust
      homebrew:
        name: rust

    - name: Homebrew Install MarkdownLint CLI
      homebrew:
        name: markdownlint-cli

    - name: Cargo install bindgen
      command: cargo install bindgen
      become: yes
      become_user: phasicj-ci

    - name: Fetch ~/.profile
      copy:
        src: files/shells/profile
        dest: "/Users/phasicj-ci/.profile"
        owner: phasicj-ci
      become: yes

    - name: Fetch ~/.zshrc
      copy:
        src: files/shells/zshrc
        dest: "/Users/phasicj-ci/.zshrc"
        owner: phasicj-ci
      become: yes
